# Chainlink Automation — Supported Networks
# https://docs.chain.link/chainlink-automation/overview/supported-networks
# https://docs.chain.link/resources/link-token-contracts

# Arbitrum One
42161:
  name: Arbitrum One
  linkAddress: "0xf97f4df75117a78c1A5a0DBb814Af92458539FB4"
  registryAddress: "0x37D9dC70bfcd8BC77Ec2858836B923c560E891D1"
  registrarAddress: "0x86EFBD0b6736Bed994962f9797049422A3A8E8Ad"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 2000
  gasCeilingMultiplier: 5
  minUpkeepSpendLINK: 0.1

# Arbitrum Sepolia
421614:
  name: Arbitrum Sepolia
  linkAddress: "0xb1D4538B4571d411F07960EF2838Ce337FE1E80E"
  registryAddress: "0x8194399B3f11fcA2E8cCEfc4c9A658c61B8Bf412"
  registrarAddress: "0x881918E24290084409DaA91979A30e6f0dB52eBe"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 2000
  gasCeilingMultiplier: 5
  minUpkeepSpendLINK: 0.1

# Avalanche Mainnet
43114:
  name: Avalanche Mainnet
  linkAddress: "0x5947BB275c521040051D82396192181b413227A3"
  registryAddress: "0x7f00a3Cd4590009C349192510D51F8e6312E08CB"
  registrarAddress: "0x5Cb7B29e621810Ce9a04Bee137F8427935795d00"
  paymentPremiumPercent: 40
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.1

# Avalanche Fuji Testnet
43113:
  name: Avalanche Fuji
  linkAddress: "0x0b9d5D9136855f6FEc3c0993feE6E9CE8a297846"
  registryAddress: "0x819B58A646CDd8289275A87653a2aA4902b14fe6"
  registrarAddress: "0xD23D3D1b81711D75E1012211f1b65Cc7dBB474e2"
  paymentPremiumPercent: 40
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.0

# Base Mainnet
8453:
  name: Base Mainnet
  linkAddress: "0x88Fb150BDc53A65fe94Dea0c9BA0a6dAf8C6e196"
  registryAddress: "0xf4bAb6A129164aBa9B113cB96BA4266dF49f8743"
  registrarAddress: "0xE28Adc50c7551CFf69FCF32D45d037e5F6554264"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 2000
  gasCeilingMultiplier: 5
  minUpkeepSpendLINK: 0.1

# Base Sepolia Testnet
84532:
  name: Base Sepolia
  linkAddress: "0xE4aB69C077896252FAFBD49EFD26B5D171A32410"
  registryAddress: "0x91D4a4C3D448c7f3CB477332B1c7D420a5810aC3"
  registrarAddress: "0xf28D56F3A707E25B71Ce529a21AF388751E1CF2A"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 1000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.1

# BNB Chain Mainnet
56:
  name: BNB Chain Mainnet
  linkAddress: "0x404460C6A5EdE2D891e8297795264fDe62ADBB75"
  registryAddress: "0xDc21E279934fF6721CaDfDD112DAfb3261f09A2C"
  registrarAddress: "0xf671F60bCC964B309D22424886FF202807381B32"
  paymentPremiumPercent: 30
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.1

# BNB Chain Testnet
97:
  name: BNB Chain Testnet
  linkAddress: "0x84b9B910527Ad5C03A9Ca831909E21e236EA7b06"
  registryAddress: "0x96bb60aAAec09A0FceB4527b81bbF3Cc0c171393"
  registrarAddress: "0x0631ea498c2Cd8371B020b9eC03f5F779174562B"
  paymentPremiumPercent: 30
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.0

# Ethereum Mainnet
1:
  name: Ethereum Mainnet
  linkAddress: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
  registryAddress: "0x6593c7De001fC8542bB1703532EE1E5aA0D458fD"
  registrarAddress: "0x6B0B234fB2f380309D47A7E9391E29E9a179395a"
  paymentPremiumPercent: 20
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 2000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.1

# Ethereum Sepolia Testnet
11155111:
  name: Ethereum Sepolia
  linkAddress: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
  registryAddress: "0x86EFBD0b6736Bed994962f9797049422A3A8E8Ad"
  registrarAddress: "0xb0E49c5D0d05cbc241d68c05BC5BA1d1B7B72976"
  paymentPremiumPercent: 20
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 2000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.0

# Gnosis Mainnet
100:
  name: Gnosis Mainnet
  linkAddress: "0xE2e73A1c69ecF83F464EFBD1340622313e7910F0"
  registryAddress: "0x299c92a219F61a82E91d2062A262f7157F155AC1"
  registrarAddress: "0x0F7E163446AAb41DB5375AbdeE2c3eCC56D9aA32"
  paymentPremiumPercent: 100
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.1

# Gnosis Chiado Testnet
10200:
  name: Gnosis Chiado
  linkAddress: "0xDCA67FD8324990792C0bfaE95903B8A64097754F"
  registryAddress: "0x2CA3BC9eC81E9647e7f8e7EdFE630a27A4E470dB"
  registrarAddress: "0xcfB98e8E3AB99217a0E61C29f86ba3a4B79037BF"
  paymentPremiumPercent: 30
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.1

# OP Mainnet
10:
  name: OP Mainnet
  linkAddress: "0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6"
  registryAddress: "0x4F70c323b8B72AeffAF633Aa4D5e8B6Be5df4AEf"
  registrarAddress: "0xe96057F85510292231e2C759752f012C87A8c8dd"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 5

# OP Sepolia Testnet
11155420:
  name: OP Sepolia
  linkAddress: "0xE4aB69C077896252FAFBD49EFD26B5D171A32410"
  registryAddress: "0x8E82eE417f916Bd44E8Efa144222808E5Fa84611"
  registrarAddress: "0x9e329384F4155a5c284FF91CeD9f2AEF589C81c9"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 5
  minUpkeepSpendLINK: 0.1

# Polygon Mainnet
137:
  name: Polygon Mainnet
  linkAddress: "0xb0897686c545045aFc77CF20eC7A532E3120E0F1"
  registryAddress: "0x08a8eea76D2395807Ce7D1FC942382515469cCA1"
  registrarAddress: "0x0Bc5EDC7219D272d9dEDd919CE2b4726129AC02B"
  paymentPremiumPercent: 70
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.1

# Polygon Amoy Testnet
80002:
  name: Polygon Amoy
  linkAddress: "0x0Fd9e8d3aF1aaee056EB9e802c3A762a667b1904"
  registryAddress: "0x93C0e201f7B158F503a1265B6942088975f92ce7"
  registrarAddress: "0x99083A4bb154B0a3EC7a0D1eb40370C892Db4225"
  paymentPremiumPercent: 30
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 3
  minUpkeepSpendLINK: 0.1

# Polygon zkEVM Mainnet
1101:
  name: Polygon zkEVM Mainnet
  linkAddress: "0xdB7A504CF869484dd6aC5FaF925c8386CBF7573D"
  registryAddress: "0x0F7E163446AAb41DB5375AbdeE2c3eCC56D9aA32"
  registrarAddress: "0x703C1d261a996755409c74d00871e7D6Af4d9896"
  paymentPremiumPercent: 56
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.0004

# Polygon zkEVM Cardona Testnet
2442:
  name: Polygon zkEVM Cardona
  linkAddress: "0x5576815a38A3706f37bf815b261cCc7cCA77e975"
  registryAddress: "0x0F7E163446AAb41DB5375AbdeE2c3eCC56D9aA32"
  registrarAddress: "0x703C1d261a996755409c74d00871e7D6Af4d9896"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.0004

# Scroll Mainnet
534352:
  name: Scroll Mainnet
  linkAddress: "0x548C6944cba02B9D1C0570102c89de64D258d3Ac"
  registryAddress: "0xBe55E7eb27Cd69Be0883E0284632A91bB7AdC272"
  registrarAddress: "0x80C55e674a34FfE730B0357E16e8852B19573f7C"
  paymentPremiumPercent: 56
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.0004

# Scroll Sepolia Testnet
534351:
  name: Scroll Sepolia
  linkAddress: "0x231d45b53C905c3d6201318156BDC725c9c3B9B1"
  registryAddress: "0x93C0e201f7B158F503a1265B6942088975f92ce7"
  registrarAddress: "0x8ee44ab698169a0AcA2571834b19a02d09D818d5"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.1

# ZkSync Mainnet
324:
  name: ZkSync Mainnet
  linkAddress: "0x52869bae3E091e36b0915941577F2D47d8d8B534"
  registryAddress: "0x8D405a2252fe4bd50dF29835e621986E59A81D74"
  registrarAddress: "0x7415C4E9758F3cA26F1a4a8F11d885eadEF68939"
  paymentPremiumPercent: 50
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.0004

# ZkSync Sepolia Testnet
300:
  name: ZkSync Sepolia
  linkAddress: "0x23A1aFD896c8c8876AF46aDc38521f4432658d1e"
  registryAddress: "0xc740003833d487c49881Cd19A21B8c58313e0cF4"
  registrarAddress: "0xC23751714a66B9824Fa6724A7B08635D480e88cD"
  paymentPremiumPercent: 30
  blockCountPerTurn: null
  maxCheckDataSize: 5000
  checkGasLimit: 10000000
  performGasLimit: 5000000
  maxPerformDataSize: 5000
  gasCeilingMultiplier: 2
  minUpkeepSpendLINK: 0.0004
